POST http://localhost:3333/videos
Content-Type: application/json

{
    "titulo":"Video Node",
    "descricao": "primeiro video",
    "duracao":180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/5fb99910-0b09-4457-b3c8-80009ac680b0
Content-Type: application/json

{
    "titulo":"Video 02",
    "descricao": "primeiro video",
    "duracao":180
}

###

DELETE http://localhost:3333/videos/5019a2b4-37a1-42b1-a0cd-c5728ca8067d

###

GET http://localhost:3333/videos?search=node
